filename = 'Accidentdata.csv' ;
opts = detectImportOptions(filename) ;

Accidents = readtable('Accidentdata.csv',opts) ; 

roads = table(Accidents.Road_Type) ; 
roads.Properties.VariableNames = {'Road_Type'} ;

roads.NumberOfAccidents(:) = 1 ;

NoofaccidentsByRoadType = varfun(@sum,...
                                 roads,...
                                 'GroupingVariables',...
                                 'Road_Type',...
                                 'InputVariables',...
                                 'NumberOfAccidents') ;
                             
NoofaccidentsByRoadType = removevars(NoofaccidentsByRoadType,...
                                    {'GroupCount'});
                                
NoofaccidentsByRoadType.Properties.VariableNames = {'Road_Type',...
                                                    'NumberOfAccidents'} ;