filename = 'Accidentdata.csv' ;
opts = detectImportOptions(filename) ;

Accidents = readtable('Accidentdata.csv',opts) ; 

roads = table(Accidents.x1st_Road_Class,...
              Accidents.x1st_Road_Number,...
              Accidents.Latitude,...
              Accidents.Longitude) ; 
roads.Properties.VariableNames = {'Road_class',...
                                  'Road_Number',...
                                  'Latitude',...
                                  'Longitude'} ;
   
roads.NumberOfAccidents(:) = 1 ;
                              
NoofaccidentsByRoadType = varfun(@sum,...
                                 roads,...
                                 'GroupingVariables',...
                                 {'Road_Number',...
                                 'Road_class'},...
                                 'InputVariables',...
                                 'NumberOfAccidents') ;
                             
NoofaccidentsByRoadType = removevars(NoofaccidentsByRoadType,...
                                    {'GroupCount'});

                                
a = table2array(roads) ;
[G,D1,D2] = findgroups(a(:,1),a(:,2));
Lat = splitapply(@mean,a(:, 3),G) ;
long = splitapply(@mean,a(:, 4),G) ;
result = [D1, D2, Lat, long] ;

longlatroads = array2table(result) ;
longlatroads.Properties.VariableNames = {'Road_class',...
                                         'Road_Number',...
                                         'Latitude',...
                                         'Longitude'} ;
joinedroadnumbers = join(NoofaccidentsByRoadType,longlatroads);

joinedroadnumbers = sortrows(joinedroadnumbers,...
                            'Road_Number',...
                            'ascend');

joinedroadnumbers(joinedroadnumbers.Road_Number == 0 , : ) = [] ; 

% joinedroadnumbers(joinedroadnumbers.sum_NumberOfAccidents <= 5 , : ) = [] ; 

                        
figure
gb = geobubble(joinedroadnumbers,'Latitude','Longitude',...
               'SizeVariable','sum_NumberOfAccidents');
gb.SourceTable.RoadDanger = discretize(joinedroadnumbers.sum_NumberOfAccidents,...
                                       [0 10 100 300 1000],...
                                       'categorical',...
                                       {'Low',...
                                        'Medium',...
                                        'High'...
                                        'Extreme'});
gb.ColorVariable = 'RoadDanger';
% gb.BubbleColorList = autumn(4);
% 
% neworder = {'Extreme',...
%             'High',...
%             'Medium',...
%             'Low'};
% gb.SourceTable.RoadDanger = reordercats(gb.SourceTable.RoadDanger,...
%                                         neworder);
title 'Number of accidents per road AUG - DEC 2017'
gb.SizeLegendTitle = 'Number of Accidents';
gb.ColorLegendTitle = 'Danger of roads';