%read in files
filename = 'Accidentdata.csv' ;
opts = detectImportOptions(filename) ;

Accidents = readtable(filename,opts) ; 

filename = 'justroads.csv' ;
opts = detectImportOptions(filename) ;

roadnumbers = readtable(filename,opts) ; 

%get roads that accidents take place on

roads = table(Accidents.x1st_Road_Class,...
              Accidents.x1st_Road_Number) ; 
roads.Properties.VariableNames = {'RoadClass',...
                                  'RoadNumber'} ;
%find roads where accidents didnt take place 
missingroads = setdiff(roadnumbers,roads) ; 
%calculate number of accidents on the roads 
roads.NumberOfAccidents(:) = 1 ;
                              
NoofaccidentsByRoadType = varfun(@sum,...
                                 roads,...
                                 'GroupingVariables',...
                                 {'RoadNumber',...
                                 'RoadClass'},...
                                 'InputVariables',...
                                 'NumberOfAccidents') ;
NoofaccidentsByRoadType = removevars(NoofaccidentsByRoadType,...
                                    {'GroupCount'});
NoofaccidentsByRoadType = sortrows(NoofaccidentsByRoadType,...
                                   'RoadNumber',...
                                   'ascend');
%find average accident severity for each road 
                                
 AvgSeverityByRoad = varfun(@mean,...
                            Accidents,...
                            'GroupingVariables',...
                            {'x1st_Road_Class',...
                            'x1st_Road_Number'},...
                            'InputVariables',...
                            'Accident_Severity') ;
             
AvgSeverityByRoad = removevars(AvgSeverityByRoad,...
                              {'GroupCount'});
AvgSeverityByRoad = sortrows(AvgSeverityByRoad,...
                             'x1st_Road_Number',...
                             'ascend');
%take average number of vehicles involved in the accidents on each road                           
AvgNoOfVehiclesByRoad = varfun(@mean,...
                               Accidents,...
                               'GroupingVariables',...
                               {'x1st_Road_Class',...
                               'x1st_Road_Number'},...
                               'InputVariables',...
                               'Number_of_Vehicles') ;
AvgNoOfVehiclesByRoad = removevars(AvgNoOfVehiclesByRoad,...
                                   {'GroupCount'}); 
AvgNoOfVehiclesByRoad = sortrows(AvgNoOfVehiclesByRoad,...
                                'x1st_Road_Number',...
                                'ascend');
%find average number of casulaties for accidents on a road
AvgNoOfCasulaties = varfun(@mean,...
                           Accidents,...
                           'GroupingVariables',...
                           {'x1st_Road_Class',...
                           'x1st_Road_Number'},...
                           'InputVariables',...
                           'Number_of_Casualties') ;
       
AvgNoOfCasulaties = removevars(AvgNoOfCasulaties,...
                                   {'GroupCount'}); 
AvgNoOfCasulaties = sortrows(AvgNoOfCasulaties,...
                            'x1st_Road_Number',...
                            'ascend');
                               
%combine all these results 

AveragesOfAccidents = table(NoofaccidentsByRoadType.RoadNumber,...
                            NoofaccidentsByRoadType.RoadClass,...
                            NoofaccidentsByRoadType.sum_NumberOfAccidents,...
                            AvgSeverityByRoad.mean_Accident_Severity,...
                            AvgNoOfVehiclesByRoad.mean_Number_of_Vehicles,...
                            AvgNoOfCasulaties.mean_Number_of_Casualties) ;
                        
AveragesOfAccidents.Properties.VariableNames = {'RoadNumber'...
                                                'RoadClass'...
                                                'NumberOfAccidents'...
                                                'AvgAccidentSeverity'...
                                                'avgNoOfVehicles'...
                                                'avgNoOfCasualties'} ;
% add the midding variables to the missing roads table
missingroads.NumberOfAccidents(:) = 0 ;
missingroads.AvgAccidentSeverity(:) = 0 ;
missingroads.avgNoOfVehicles(:) = 0 ;
missingroads.avgNoOfCasualties(:) = 0 ;

%add the missing roads to the table
finishedtable = [AveragesOfAccidents;missingroads]  ;

%catagorise data for training

severitycatagory = varfun(@catSev,...
                           finishedtable,...
                           'GroupingVariables',...
                           {'RoadClass',...
                           'RoadNumber'},...
                           'InputVariables',...
                           'AvgAccidentSeverity') ;
severitycatagory = sortrows(severitycatagory,...
                           'RoadNumber',...
                           'ascend');
 
NoAcccatagory = varfun(@catAccNo,...
                       finishedtable,...
                       'GroupingVariables',...
                       {'RoadClass',...
                       'RoadNumber'},...
                       'InputVariables',...
                       'NumberOfAccidents') ;
NoAcccatagory = sortrows(NoAcccatagory,...
                         'RoadNumber',...
                         'ascend');
                   
NoVehcatagory = varfun(@catVehNo,...
                       finishedtable,...
                       'GroupingVariables',...
                       {'RoadClass',...
                       'RoadNumber'},...
                       'InputVariables',...
                       'avgNoOfVehicles') ;
NoVehcatagory = sortrows(NoVehcatagory,...
                         'RoadNumber',...
                         'ascend');
NoCascatagory = varfun(@catCasNo,...
                       finishedtable,...
                       'GroupingVariables',...
                       {'RoadClass',...
                       'RoadNumber'},...
                       'InputVariables',...
                       'avgNoOfCasualties') ;
NoCascatagory = sortrows(NoCascatagory,...
                         'RoadNumber',...
                         'ascend');
finishedtable.DangerSum(:) = severitycatagory.catSev_AvgAccidentSeverity +...
                             NoAcccatagory.catAccNo_NumberOfAccidents +...
                             NoVehcatagory.catVehNo_avgNoOfVehicles +...
                             NoCascatagory.catCasNo_avgNoOfCasualties;
                         
catagorised = varfun(@catagorise,...
                       finishedtable,...
                       'GroupingVariables',...
                       {'RoadClass',...
                       'RoadNumber'},...
                       'InputVariables',...
                       'DangerSum') ;
catagorised = sortrows(catagorised,...
                       'RoadNumber',...
                       'ascend');
finishedtable.DangerCatagory(:) = catagorised.catagorise_DangerSum ;
%write table to file
writetable(finishedtable,...
           "finishedtable.csv");    
       
       
function x = catSev(y) 
    if y < 1
        x = 0 ; 
    elseif y >= 1 && y < 2
        x = 3 ;
    elseif y>= 2 && y < 3
        x = 2 ;
    elseif y == 3 
        x = 1 ;
    end 
end

function x = catAccNo(y) 
    if y < 1
        x = 0 ; 
    elseif y == 1 
        x = 1 ;
    elseif y > 1 && y < 3
        x = 2 ;
    elseif y >= 3 && y < 5
        x = 3 ;
    elseif y >= 5 && y < 10
        x = 4 ;
    elseif y >= 10 && y < 50
        x = 5 ;
    elseif y >= 50 
        x = 6 ;
    end 
end

function x = catVehNo(y) 
    if y < 1
        x = 0 ; 
    elseif y == 1 
        x = 1 ;
    elseif y > 1 && y < 3
        x = 2 ;
    elseif y >= 3 && y < 5
        x = 3 ;
    elseif y >= 5 
        x = 4 ;
    end 
end

function x = catCasNo(y) 
    if y < 1
        x = 0 ; 
    elseif y == 1 
        x = 1 ;
    elseif y > 1 && y < 3
        x = 2 ;
    elseif y >= 3 && y < 5
        x = 3 ;
    elseif y >= 5 
        x = 4 ;
    end 
end

function x = catagorise(y) 
    if y == 0
        x = 0 ; 
    elseif y <= 4 
        x = 1 ;
    elseif y > 4 && y <= 7
        x = 2 ;
    elseif y > 7 && y < 10
        x = 3 ;
    elseif y >= 10 
        x = 4 ;
    end 
end