%read in files
filename = 'processingstep1.csv' ;
opts = detectImportOptions(filename) ;

dataneeded = readtable(filename,opts) ; 

Weather1 = varfun(@fine,...
                dataneeded,...
                'GroupingVariables',...
                'index',...
                'InputVariables',...
                'Weather_Conditions') ;
Weather1 = removevars(Weather1,...
                    {'GroupCount'}) ;
Weather2 = varfun(@Rain,...
                dataneeded,...
                'GroupingVariables',...
                'index',...
                'InputVariables',...
                'Weather_Conditions') ;
Weather2 = removevars(Weather2,...
                    {'GroupCount'}) ;
Weather3 = varfun(@snow,...
                dataneeded,...
                'GroupingVariables',...
                'index',...
                'InputVariables',...
                'Weather_Conditions') ;
Weather3 = removevars(Weather3,...
                    {'GroupCount'}) ;
Weather4 = varfun(@windy,...
                dataneeded,...
                'GroupingVariables',...
                'index',...
                'InputVariables',...
                'Weather_Conditions') ;
Weather4 = removevars(Weather4,...
                    {'GroupCount'}) ;
Weather5 = varfun(@rainAndWind,...
                dataneeded,...
                'GroupingVariables',...
                'index',...
                'InputVariables',...
                'Weather_Conditions') ;
Weather5 = removevars(Weather5,...
                    {'GroupCount'}) ;
Weather6 = varfun(@snowAndWind,...
                dataneeded,...
                'GroupingVariables',...
                'index',...
                'InputVariables',...
                'Weather_Conditions') ;
Weather6 = removevars(Weather6,...
                    {'GroupCount'}) ;
Weather7 = varfun(@fog,...
                dataneeded,...
                'GroupingVariables',...
                'index',...
                'InputVariables',...
                'Weather_Conditions') ;
Weather7 = removevars(Weather7,...
                    {'GroupCount'}) ;
Weather8 = varfun(@other,...
                dataneeded,...
                'GroupingVariables',...
                'index',...
                'InputVariables',...
                'Weather_Conditions') ;
Weather8 = removevars(Weather8,...
                    {'GroupCount'}) ;
Weather9 = varfun(@unknown,...
                dataneeded,...
                'GroupingVariables',...
                'index',...
                'InputVariables',...
                'Weather_Conditions') ;
Weather9 = removevars(Weather9,...
                    {'GroupCount'}) ;
Weather0 = varfun(@noweatherdata,...
                dataneeded,...
                'GroupingVariables',...
                'index',...
                'InputVariables',...
                'Weather_Conditions') ;
Weather0 = removevars(Weather0,...
                    {'GroupCount'}) ;                 
dataneeded = join(dataneeded,Weather0) ; 
dataneeded = join(dataneeded,Weather1) ; 
dataneeded = join(dataneeded,Weather2) ; 
dataneeded = join(dataneeded,Weather3) ; 
dataneeded = join(dataneeded,Weather4) ; 
dataneeded = join(dataneeded,Weather5) ; 
dataneeded = join(dataneeded,Weather6) ; 
dataneeded = join(dataneeded,Weather7) ; 
dataneeded = join(dataneeded,Weather8) ; 
dataneeded = join(dataneeded,Weather9) ; 

vars = {'Weather0','Weather1','Weather2','Weather3','Weather4',...
        'Weather5','Weather6',...
        'Weather7','Weather8','Weather9'} ;
clear(vars{:}) ; 

DayLight = varfun(@Daylight,...
                dataneeded,...
                'GroupingVariables',...
                'index',...
                'InputVariables',...
                'Light_Conditions') ;
DayLight = removevars(DayLight,...
                    {'GroupCount'}) ; 
DarkLit = varfun(@DarkWithLights,...
                dataneeded,...
                'GroupingVariables',...
                'index',...
                'InputVariables',...
                'Light_Conditions') ;
DarkLit = removevars(DarkLit,...
                    {'GroupCount'}) ; 
DarkNotLit = varfun(@DarkLightsOut,...
                dataneeded,...
                'GroupingVariables',...
                'index',...
                'InputVariables',...
                'Light_Conditions') ;
DarkNotLit = removevars(DarkNotLit,...
                    {'GroupCount'}) ; 
DarkNoLight = varfun(@DarkNoLights,...
                dataneeded,...
                'GroupingVariables',...
                'index',...
                'InputVariables',...
                'Light_Conditions') ;
DarkNoLight = removevars(DarkNoLight,...
                    {'GroupCount'}) ; 
UnknownLights = varfun(@DarkLightsUnknown,...
                dataneeded,...
                'GroupingVariables',...
                'index',...
                'InputVariables',...
                'Light_Conditions') ;
UnknownLights = removevars(UnknownLights,...
                    {'GroupCount'}) ; 
LightMissingData = varfun(@LightDataMissing,...
                dataneeded,...
                'GroupingVariables',...
                'index',...
                'InputVariables',...
                'Light_Conditions') ;
LightMissingData = removevars(LightMissingData,...
                    {'GroupCount'}) ; 
               
dataneeded = join(dataneeded,DayLight) ; 
dataneeded = join(dataneeded,DarkLit) ; 
dataneeded = join(dataneeded,DarkNotLit) ; 
dataneeded = join(dataneeded,DarkNoLight) ; 
dataneeded = join(dataneeded,UnknownLights) ; 
dataneeded = join(dataneeded,LightMissingData) ; 

vars = {'DayLight','DarkLit','DarkNotLit','DarkNoLight','UnknownLights',...
        'LightMissingData'} ;
clear(vars{:}) ; 

dataneeded = removevars(dataneeded,...
                       {'Weather_Conditions','Light_Conditions'}); 

Roundabouts = varfun(@Roundabout,...
                dataneeded,...
                'GroupingVariables',...
                'index',...
                'InputVariables',...
                'Road_Type') ;
Roundabouts = removevars(Roundabouts,...
                    {'GroupCount'}) ; 
OneWayStreets = varfun(@OneWay,...
                dataneeded,...
                'GroupingVariables',...
                'index',...
                'InputVariables',...
                'Road_Type') ;
OneWayStreets = removevars(OneWayStreets,...
                    {'GroupCount'}) ; 
DualCarriageRoad = varfun(@DualCarriage,...
                dataneeded,...
                'GroupingVariables',...
                'index',...
                'InputVariables',...
                'Road_Type') ;
DualCarriageRoad = removevars(DualCarriageRoad,...
                    {'GroupCount'}) ; 
SingleCarriageRoad = varfun(@singleCariage,...
                dataneeded,...
                'GroupingVariables',...
                'index',...
                'InputVariables',...
                'Road_Type') ;
SingleCarriageRoad = removevars(SingleCarriageRoad,...
                    {'GroupCount'}) ; 
SlipRoads = varfun(@slip,...
                dataneeded,...
                'GroupingVariables',...
                'index',...
                'InputVariables',...
                'Road_Type') ;
SlipRoads = removevars(SlipRoads,...
                    {'GroupCount'}) ; 
Unknownroadtype = varfun(@unknownRoad,...
                dataneeded,...
                'GroupingVariables',...
                'index',...
                'InputVariables',...
                'Road_Type') ;
Unknownroadtype = removevars(Unknownroadtype,...
                    {'GroupCount'}) ; 
OneWaySlipRoad = varfun(@onewayslip,...
                dataneeded,...
                'GroupingVariables',...
                'index',...
                'InputVariables',...
                'Road_Type') ;
OneWaySlipRoad = removevars(OneWaySlipRoad,...
                    {'GroupCount'}) ; 
MissingRoadData = varfun(@roaddatamissing,...
                dataneeded,...
                'GroupingVariables',...
                'index',...
                'InputVariables',...
                'Road_Type') ;
MissingRoadData = removevars(MissingRoadData,...
                    {'GroupCount'}) ; 
        
dataneeded = join(dataneeded,Roundabouts) ; 
dataneeded = join(dataneeded,OneWayStreets) ; 
dataneeded = join(dataneeded,DualCarriageRoad) ; 
dataneeded = join(dataneeded,SingleCarriageRoad) ; 
dataneeded = join(dataneeded,SlipRoads) ; 
dataneeded = join(dataneeded,Unknownroadtype) ;   
dataneeded = join(dataneeded,OneWaySlipRoad) ; 
dataneeded = join(dataneeded,MissingRoadData) ;

vars = {'Roundabouts','OneWayStreets','DualCarriageRoad',...
        'SingleCarriageRoad','SlipRoads',...
        'Unknownroadtype','OneWaySlipRoad','MissingRoadData'} ;
clear(vars{:}) ; 

dataneeded = removevars(dataneeded,...
                       {'Road_Type'});
                   
%write table to file
writetable(dataneeded,...
           "processingstep2.csv");    

function x = fine(y) 
    if y == 1
        x = 1 ; 
    else
        x = 0 ;
    end 
end

function x = Rain(y) 
    if y == 2
        x = 1 ; 
    else
        x = 0 ;
    end 
end

function x = snow(y) 
    if y == 3
        x = 1 ; 
    else
        x = 0 ;
    end 
end

function x = windy(y) 
    if y == 4
        x = 1 ; 
    else
        x = 0 ;
    end 
end

function x = rainAndWind(y) 
    if y == 5
        x = 1 ; 
    else
        x = 0 ;
    end 
end

function x = snowAndWind(y) 
    if y == 6
        x = 1 ; 
    else
        x = 0 ;
    end 
end

function x = fog(y) 
    if y == 7
        x = 1 ; 
    else
        x = 0 ;
    end 
end

function x = other(y) 
    if y == 8
        x = 1 ; 
    else
        x = 0 ;
    end 
end

function x = unknown(y) 
    if y == 9
        x = 0 ; 
    else
        x = 0 ;
    end 
end

function x = noweatherdata(y) 
    if y == -1
        x = 0 ; 
    else
        x = 0 ;
    end 
end

function x = Daylight(y) 
    if y == 1
        x = 1 ; 
    else
        x = 0 ;
    end 
end
function x = DarkWithLights(y) 
    if y == 4
        x = 1 ; 
    else
        x = 0 ;
    end 
end
function x = DarkLightsOut(y) 
    if y == 5
        x = 1 ; 
    else
        x = 0 ;
    end 
end
function x = DarkNoLights(y) 
    if y == 6
        x = 1 ; 
    else
        x = 0 ;
    end 
end
function x = DarkLightsUnknown(y) 
    if y == 7
        x = 1 ; 
    else
        x = 0 ;
    end 
end
function x = LightDataMissing(y) 
    if y == -1
        x = 0 ; 
    else
        x = 0 ;
    end 
end
function x = Roundabout(y) 
    if y == 1
        x = 0 ; 
    else
        x = 0 ;
    end 
end
function x = OneWay(y) 
    if y == 2
        x = 0 ; 
    else
        x = 0 ;
    end 
end
function x = DualCarriage(y) 
    if y == 3
        x = 0 ; 
    else
        x = 0 ;
    end 
end
function x = singleCariage(y) 
    if y == 6
        x = 0 ; 
    else
        x = 0 ;
    end 
end
function x = slip(y) 
    if y == 7
        x = 0 ; 
    else
        x = 0 ;
    end 
end
function x = unknownRoad(y) 
    if y == 9
        x = 0 ; 
    else
        x = 0 ;
    end 
end
function x = onewayslip(y) 
    if y == 12
        x = 0 ; 
    else
        x = 0 ;
    end 
end
function x = roaddatamissing(y) 
    if y == -1
        x = 0 ; 
    else
        x = 0 ;
    end 
end
