%read in files
filename = 'Accidentdata.csv' ;
opts = detectImportOptions(filename) ;
opts = setvartype(opts,{'Time'},'string') ; 

Accidents = readtable(filename,opts) ; 

filename = 'NegativeData.csv' ;
opts = detectImportOptions(filename) ;
NegativeData = readtable(filename,opts) ; 

%remove the variables we wont be using right now 
neededdata = removevars(Accidents,...
                      {'Accident_Index',...
                       'Location_Easting_OSGR',...
                       'Location_Northing_OSGR',...
                       'Longitude',...
                       'Latitude',...
                       'Police_Force',...
                       'Local_Authority__District_',...
                       'Local_Authority__Highway_',...
                       'Junction_Control',...
                       'x2nd_Road_Class',...
                       'x2nd_Road_Number',...
                       'Did_Police_Officer_Attend_Scene_of_Accident',...
                       'LSOA_of_Accident_Location',...
                       'Date',...
                       'Time',...
                       'Pedestrian_Crossing_Human_Control',...
                       'Pedestrian_Crossing_Physical_Facilities',...
                       'Special_Conditions_at_Site',...
                       'Carriageway_Hazards',...
                       'Accident_Severity',...
                       'Number_of_Vehicles',...
                       'Number_of_Casualties'
                       });
%create an index for the new table
neededdata.IsAccident(:) = 1 ;

neededdata = [neededdata;NegativeData] ;
neededdata.index = (1:height(neededdata)).' ; 

%seperate the days of the weeks to their own variables 
Sunday = varfun(@sunday,...
                neededdata,...
                'GroupingVariables',...
                'index',...
                'InputVariables',...
                'Day_of_Week') ;
Monday = varfun(@monday,...
                neededdata,...
                'GroupingVariables',...
                'index',...
                'InputVariables',...
                'Day_of_Week') ;
Tuesday = varfun(@tuesday,...
                neededdata,...
                'GroupingVariables',...
                'index',...
                'InputVariables',...
                'Day_of_Week') ;
Wednesday = varfun(@wednesday,...
                neededdata,...
                'GroupingVariables',...
                'index',...
                'InputVariables',...
                'Day_of_Week') ;
Thursday = varfun(@thursday,...
                neededdata,...
                'GroupingVariables',...
                'index',...
                'InputVariables',...
                'Day_of_Week') ;
Friday = varfun(@friday,...
                neededdata,...
                'GroupingVariables',...
                'index',...
                'InputVariables',...
                'Day_of_Week') ;
Saturday = varfun(@saturday,...
                neededdata,...
                'GroupingVariables',...
                'index',...
                'InputVariables',...
                'Day_of_Week') ;
Sunday = removevars(Sunday,...
                    {'GroupCount'}); 
Monday = removevars(Monday,...
                    {'GroupCount'}); 
Tuesday = removevars(Tuesday,...
                    {'GroupCount'}); 
Wednesday = removevars(Wednesday,...
                    {'GroupCount'}); 
Thursday = removevars(Thursday,...
                    {'GroupCount'}); 
Friday = removevars(Friday,...
                    {'GroupCount'}); 
Saturday = removevars(Saturday,...
                    {'GroupCount'}); 
neededdata = join(neededdata,Sunday) ; 
neededdata = join(neededdata,Monday) ;
neededdata = join(neededdata,Tuesday) ;
neededdata = join(neededdata,Wednesday) ;
neededdata = join(neededdata,Thursday) ;
neededdata = join(neededdata,Friday) ;
neededdata = join(neededdata,Saturday) ;

%remove the new tables from workspace to free memory
vars = {'Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'} ;
clear(vars{:}) ; 

%remove the weekday variable as no longer needed

neededdata = removevars(neededdata,...
                      {'Day_of_Week'});

%seperate hours of the day 
Hours00 = varfun(@hour0,...
                neededdata,...
                'GroupingVariables',...
                'index',...
                'InputVariables',...
                'DateTime') ;
Hours00 = removevars(Hours00,...
                    {'GroupCount'}); 
Hours01 = varfun(@hour1,...
                neededdata,...
                'GroupingVariables',...
                'index',...
                'InputVariables',...
                'DateTime') ;
Hours01 = removevars(Hours01,...
                    {'GroupCount'}); 
Hours02 = varfun(@hour2,...
                neededdata,...
                'GroupingVariables',...
                'index',...
                'InputVariables',...
                'DateTime') ;
Hours02 = removevars(Hours02,...
                    {'GroupCount'}); 
Hours03 = varfun(@hour3,...
                neededdata,...
                'GroupingVariables',...
                'index',...
                'InputVariables',...
                'DateTime') ;
Hours03 = removevars(Hours03,...
                    {'GroupCount'}); 
Hours04 = varfun(@hour4,...
                neededdata,...
                'GroupingVariables',...
                'index',...
                'InputVariables',...
                'DateTime') ;
Hours04 = removevars(Hours04,...
                    {'GroupCount'}); 
Hours05 = varfun(@hour5,...
                neededdata,...
                'GroupingVariables',...
                'index',...
                'InputVariables',...
                'DateTime') ;
Hours05 = removevars(Hours05,...
                    {'GroupCount'}); 
Hours06 = varfun(@hour6,...
                neededdata,...
                'GroupingVariables',...
                'index',...
                'InputVariables',...
                'DateTime') ;
Hours06 = removevars(Hours06,...
                    {'GroupCount'}); 
Hours07 = varfun(@hour7,...
                neededdata,...
                'GroupingVariables',...
                'index',...
                'InputVariables',...
                'DateTime') ;
Hours07 = removevars(Hours07,...
                    {'GroupCount'}); 
Hours08 = varfun(@hour8,...
                neededdata,...
                'GroupingVariables',...
                'index',...
                'InputVariables',...
                'DateTime') ;
Hours08 = removevars(Hours08,...
                    {'GroupCount'}); 
Hours09 = varfun(@hour9,...
                neededdata,...
                'GroupingVariables',...
                'index',...
                'InputVariables',...
                'DateTime') ;
Hours09 = removevars(Hours09,...
                    {'GroupCount'}); 
Hours10 = varfun(@hour10,...
                neededdata,...
                'GroupingVariables',...
                'index',...
                'InputVariables',...
                'DateTime') ;
Hours10 = removevars(Hours10,...
                    {'GroupCount'}); 
Hours11 = varfun(@hour11,...
                neededdata,...
                'GroupingVariables',...
                'index',...
                'InputVariables',...
                'DateTime') ;
Hours11 = removevars(Hours11,...
                    {'GroupCount'}); 
Hours12 = varfun(@hour12,...
                neededdata,...
                'GroupingVariables',...
                'index',...
                'InputVariables',...
                'DateTime') ;
Hours12 = removevars(Hours12,...
                    {'GroupCount'}); 
Hours13 = varfun(@hour13,...
                neededdata,...
                'GroupingVariables',...
                'index',...
                'InputVariables',...
                'DateTime') ;
Hours13 = removevars(Hours13,...
                    {'GroupCount'}); 
Hours14 = varfun(@hour14,...
                neededdata,...
                'GroupingVariables',...
                'index',...
                'InputVariables',...
                'DateTime') ;
Hours14 = removevars(Hours14,...
                    {'GroupCount'}); 
Hours15 = varfun(@hour15,...
                neededdata,...
                'GroupingVariables',...
                'index',...
                'InputVariables',...
                'DateTime') ;
Hours15 = removevars(Hours15,...
                    {'GroupCount'}); 
Hours16 = varfun(@hour16,...
                neededdata,...
                'GroupingVariables',...
                'index',...
                'InputVariables',...
                'DateTime') ;
Hours16 = removevars(Hours16,...
                    {'GroupCount'}); 
Hours17 = varfun(@hour17,...
                neededdata,...
                'GroupingVariables',...
                'index',...
                'InputVariables',...
                'DateTime') ;
Hours17 = removevars(Hours17,...
                    {'GroupCount'}); 
Hours18 = varfun(@hour18,...
                neededdata,...
                'GroupingVariables',...
                'index',...
                'InputVariables',...
                'DateTime') ;
Hours18 = removevars(Hours18,...
                    {'GroupCount'}); 
Hours19 = varfun(@hour19,...
                neededdata,...
                'GroupingVariables',...
                'index',...
                'InputVariables',...
                'DateTime') ;
Hours19 = removevars(Hours19,...
                    {'GroupCount'}); 
Hours20 = varfun(@hour20,...
                neededdata,...
                'GroupingVariables',...
                'index',...
                'InputVariables',...
                'DateTime') ;
Hours20 = removevars(Hours20,...
                    {'GroupCount'}); 
Hours21 = varfun(@hour21,...
                neededdata,...
                'GroupingVariables',...
                'index',...
                'InputVariables',...
                'DateTime') ;
Hours21 = removevars(Hours21,...
                    {'GroupCount'}); 
Hours22 = varfun(@hour22,...
                neededdata,...
                'GroupingVariables',...
                'index',...
                'InputVariables',...
                'DateTime') ;
Hours22 = removevars(Hours22,...
                    {'GroupCount'}); 
Hours23 = varfun(@hour23,...
                neededdata,...
                'GroupingVariables',...
                'index',...
                'InputVariables',...
                'DateTime') ;
Hours23 = removevars(Hours23,...
                    {'GroupCount'}) ;
neededdata = join(neededdata,Hours00) ; 
neededdata = join(neededdata,Hours01) ; 
neededdata = join(neededdata,Hours02) ; 
neededdata = join(neededdata,Hours03) ; 
neededdata = join(neededdata,Hours04) ; 
neededdata = join(neededdata,Hours05) ; 
neededdata = join(neededdata,Hours06) ; 
neededdata = join(neededdata,Hours07) ; 
neededdata = join(neededdata,Hours08) ; 
neededdata = join(neededdata,Hours09) ; 
neededdata = join(neededdata,Hours10) ; 
neededdata = join(neededdata,Hours11) ; 
neededdata = join(neededdata,Hours12) ; 
neededdata = join(neededdata,Hours13) ; 
neededdata = join(neededdata,Hours14) ; 
neededdata = join(neededdata,Hours15) ; 
neededdata = join(neededdata,Hours16) ; 
neededdata = join(neededdata,Hours17) ; 
neededdata = join(neededdata,Hours18) ; 
neededdata = join(neededdata,Hours19) ; 
neededdata = join(neededdata,Hours20) ; 
neededdata = join(neededdata,Hours21) ; 
neededdata = join(neededdata,Hours22) ; 
neededdata = join(neededdata,Hours23) ; 

vars = {'Hours00','Hours01','Hours02','Hours03','Hours04','Hours05','Hours06',...
        'Hours07','Hours08','Hours09','Hours10','Hours11','Hours12','Hours13',...
        'Hours14','Hours15','Hours16','Hours17','Hours18','Hours19','Hours20',...
        'Hours21','Hours22','Hours23'} ;
clear(vars{:}) ; 

%write table to file
writetable(neededdata,...
           "processingstep1.csv");    

function x = sunday(y) 
    if y == 1
        x = 1 ; 
    else
        x = 0 ;
    end 
end
function x = monday(y) 
    if y == 2
        x = 1 ; 
    else
        x = 0 ;
    end 
end
function x = tuesday(y) 
    if y == 3
        x = 1 ; 
    else
        x = 0 ;
    end 
end
function x = wednesday(y) 
    if y == 4
        x = 1 ; 
    else
        x = 0 ;
    end 
end
function x = thursday(y) 
    if y == 5
        x = 1 ; 
    else
        x = 0 ;
    end 
end
function x = friday(y) 
    if y == 6
        x = 1 ; 
    else
        x = 0 ;
    end 
end
function x = saturday(y) 
    if y == 7
        x = 1 ; 
    else
        x = 0 ;
    end 
end

function x = hour0(y) 
    if hour(y) == 00
        x = 1 ; 
    else
        x = 0 ;
    end 
end

function x = hour1(y) 
    if hour(y) == 01
        x = 1 ; 
    else
        x = 0 ;
    end 
end
function x = hour2(y) 
    if hour(y) == 02
        x = 1 ; 
    else
        x = 0 ;
    end 
end

function x = hour3(y) 
    if hour(y) == 03
        x = 1 ; 
    else
        x = 0 ;
    end 
end
function x = hour4(y) 
    if hour(y) == 04
        x = 1 ; 
    else
        x = 0 ;
    end 
end
function x = hour5(y) 
    if hour(y) == 05
        x = 1 ; 
    else
        x = 0 ;
    end 
end
function x = hour6(y) 
    if hour(y) == 06
        x = 1 ; 
    else
        x = 0 ;
    end 
end
function x = hour7(y) 
    if hour(y) == 07
        x = 1 ; 
    else
        x = 0 ;
    end 
end
function x = hour8(y) 
    if hour(y) == 08
        x = 1 ; 
    else
        x = 0 ;
    end 
end
function x = hour9(y) 
    if hour(y) == 09
        x = 1 ; 
    else
        x = 0 ;
    end 
end
function x = hour10(y) 
    if hour(y) == 10
        x = 1 ; 
    else
        x = 0 ;
    end 
end
function x = hour11(y) 
    if hour(y) == 11
        x = 1 ; 
    else
        x = 0 ;
    end 
end
function x = hour12(y) 
    if hour(y) == 12
        x = 1 ; 
    else
        x = 0 ;
    end 
end
function x = hour13(y) 
    if hour(y) == 13
        x = 1 ; 
    else
        x = 0 ;
    end 
end
function x = hour14(y) 
    if hour(y) == 14
        x = 1 ; 
    else
        x = 0 ;
    end 
end
function x = hour15(y) 
    if hour(y) == 15
        x = 1 ; 
    else
        x = 0 ;
    end 
end
function x = hour16(y) 
    if hour(y) == 16
        x = 1 ; 
    else
        x = 0 ;
    end 
end
function x = hour17(y) 
    if hour(y) == 17
        x = 1 ; 
    else
        x = 0 ;
    end 
end
function x = hour18(y) 
    if hour(y) == 18
        x = 1 ; 
    else
        x = 0 ;
    end 
end
function x = hour19(y) 
    if hour(y) == 19
        x = 1 ; 
    else
        x = 0 ;
    end 
end
function x = hour20(y) 
    if hour(y) == 20
        x = 1 ; 
    else
        x = 0 ;
    end 
end
function x = hour21(y) 
    if hour(y) == 21
        x = 1 ; 
    else
        x = 0 ;
    end 
end
function x = hour22(y) 
    if hour(y) == 22
        x = 1 ; 
    else
        x = 0 ;
    end 
end
function x = hour23(y) 
    if hour(y) == 23
        x = 1 ; 
    else
        x = 0 ;
    end 
end
