%read in files
filename = 'Accidentdata.csv' ;
opts = detectImportOptions(filename) ;
Accidents = readtable(filename,opts) ; 

Accidents = removevars(Accidents,...
                      {'Accident_Index',...
                       'Location_Easting_OSGR',...
                       'Location_Northing_OSGR',...
                       'Longitude',...
                       'Latitude',...
                       'Police_Force',...
                       'Local_Authority__District_',...
                       'Local_Authority__Highway_',...
                       'Junction_Control',...
                       'Did_Police_Officer_Attend_Scene_of_Accident',...
                       'LSOA_of_Accident_Location',...
                       'Date',...
                       'Time',...
                       'Pedestrian_Crossing_Human_Control',...
                       'Pedestrian_Crossing_Physical_Facilities',...
                       'Special_Conditions_at_Site',...
                       'Carriageway_Hazards',...
                       'x2nd_Road_Class',...
                       'x2nd_Road_Number'
                       });
                   
DateAndAccidents = table(Accidents.DateTime) ; 

DateAndAccidents.Accident(:) = 1;

DateAndAccidents.month = month(DateAndAccidents.Var1) ;

accidentbyMonth = varfun(@sum,...
                  DateAndAccidents,...
                  'GroupingVariables',...
                  'month',...
                  'InputVariables',...
                  'Accident') ;
accidentbyMonth = removevars(accidentbyMonth,...
                              {'GroupCount'}); 
                          
accbymonthgrapg = bar(accidentbyMonth.month,accidentbyMonth.sum_Accident) ; 


severityanddate = table(Accidents.DateTime,Accidents.Accident_Severity) ; 
severityanddate.Accident(:) = 1;
severityanddate.month = month(severityanddate.Var1) ;
severityanddate.Properties.VariableNames = {'DateTime',...
                                              'Severity',...
                                              'Accident',...
                                              'month'} ;
accidentsev1 = severityanddate ;

accidentsev1(ismember(accidentsev1.Severity,2),:) = [] ;
accidentsev1(ismember(accidentsev1.Severity,3),:) = [] ;

accidentsev2 = severityanddate ;

accidentsev2(ismember(accidentsev2.Severity,1),:) = [] ;
accidentsev2(ismember(accidentsev2.Severity,3),:) = [] ;

accidentsev3 = severityanddate ;

accidentsev3(ismember(accidentsev3.Severity,2),:) = [] ;
accidentsev3(ismember(accidentsev3.Severity,1),:) = [] ;

accidentsev1 = varfun(@sum,...
                  accidentsev1,...
                  'GroupingVariables',...
                  'month',...
                  'InputVariables',...
                  'Accident') ;
              
accidentsev2 = varfun(@sum,...
                  accidentsev2,...
                  'GroupingVariables',...
                  'month',...
                  'InputVariables',...
                  'Accident') ;
              
accidentsev3 = varfun(@sum,...
                  accidentsev3,...
                  'GroupingVariables',...
                  'month',...
                  'InputVariables',...
                  'Accident') ;
accidentsev1 = removevars(accidentsev1,...
                              {'GroupCount'}); 
accidentsev2 = removevars(accidentsev2,...
                              {'GroupCount'}); 
accidentsev3 = removevars(accidentsev3,...
                              {'GroupCount'}); 
accidentsev1.Properties.VariableNames = {'month',...
                                         'NoOfSeverity1'} ;
accidentsev2.Properties.VariableNames = {'month',...
                                         'NoOfSeverity2'} ;
accidentsev3.Properties.VariableNames = {'month',...
                                         'NoOfSeverity3'} ;
noSeverityAccByMonth = join(accidentsev1,accidentsev2) ; 
noSeverityAccByMonth = join(noSeverityAccByMonth,accidentsev3) ; 

sevbymonthbar = bar(categorical(noSeverityAccByMonth{1:12,1}),...
                                noSeverityAccByMonth{1:12,2:4}) ; 
                            
vehiclesovertimescatter = scatter(Accidents.DateTime,...
                                  Accidents.Number_of_Vehicles,4);
                              
weathertimescatter = scatter(Accidents.DateTime,...
                             Accidents.Weather_Conditions) ; 
                         
Accidents.Accident(:) = 1;

noofaccforlight = varfun(@sum,...
                  Accidents,...
                  'GroupingVariables',...
                  'Light_Conditions',...
                  'InputVariables',...
                  'Accident') ;
              
lightbynum = bar(noofaccforlight.Light_Conditions,...
                 noofaccforlight.sum_Accident) ; 
             

hourAndAccidents = table(Accidents.DateTime) ; 

hourAndAccidents.Accident(:) = 1;

hourAndAccidents.hour = hour(hourAndAccidents.Var1) ;

accidentbyHour = varfun(@sum,...
                  hourAndAccidents,...
                  'GroupingVariables',...
                  'hour',...
                  'InputVariables',...
                  'Accident') ;
accidentbyHour = removevars(accidentbyHour,...
                              {'GroupCount'}); 
                          
accbyhourgrapg = bar(accidentbyHour.hour,accidentbyHour.sum_Accident) ; 

noofaccforroad = varfun(@sum,...
                         Accidents,...
                         'GroupingVariables',...
                        'Road_Type',...
                        'InputVariables',...
                         'Accident') ;
              
roadtypebynum = bar(noofaccforroad.Road_Type,...
                 noofaccforroad.sum_Accident) ; 


noofaccforjunc = varfun(@sum,...
                         Accidents,...
                         'GroupingVariables',...
                        'Junction_Detail',...
                        'InputVariables',...
                         'Accident') ;
              
juncbynum = bar(noofaccforjunc.Junction_Detail,...
                 noofaccforjunc.sum_Accident) ; 